on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: scientific-python/circleci-artifacts-redirector-action@7eafdb60666f57706a5525a2f5eb76224dc8779b  # v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/docs/_build/html/index.html
          circleci-jobs: build_docs
