name: Push to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          persist-credentials: false

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install mpl-sphinx-theme
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Build mpl-sphinx-theme dist
        run: |
          python -m pip install wheel twine
          python setup.py sdist bdist_wheel

      - name: Publish mpl-sphinx-theme
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
