---

name: Release
on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: Build Release Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        id: setup
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build packages
        run: python -m build

      - name: Save built packages as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: packages-${{ runner.os }}-${{ steps.setup.outputs.python-version }}
          path: dist/
          if-no-files-found: error
          retention-days: 5

  publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - name: Download packages
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0  # v5.0.0
        with:
          pattern: packages-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
