---

name: Release
on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: Build Release Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        id: setup
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build packages
        run: python -m build

      - name: Save built packages as artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: packages-${{ runner.os }}-${{ steps.setup.outputs.python-version }}
          path: dist/
          if-no-files-found: error
          retention-days: 5

  publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - name: Download packages
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16  # v4.1.8
        with:
          pattern: packages-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
